//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaiaCore.Gaia.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GaiaCore.Gaia.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 牺牲1能量1个智慧石兑换1个矿石 的本地化字符串。
        /// </summary>
        internal static string Burn1Convert1BSTo1Ore {
            get {
                return ResourceManager.GetString("Burn1Convert1BSTo1Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 牺牲1能量1个智慧石兑换3点信用点 的本地化字符串。
        /// </summary>
        internal static string Burn1Convert1BSTo3Credits {
            get {
                return ResourceManager.GetString("Burn1Convert1BSTo3Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个智慧石和1点能量兑换1点知识 的本地化字符串。
        /// </summary>
        internal static string Convert1BS1PWTo1Knowledge {
            get {
                return ResourceManager.GetString("Convert1BS1PWTo1Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个智慧石和1点能量兑换1个量子方块 的本地化字符串。
        /// </summary>
        internal static string Convert1BS1PWTo1QIC {
            get {
                return ResourceManager.GetString("Convert1BS1PWTo1QIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个智慧石兑换1个矿石 的本地化字符串。
        /// </summary>
        internal static string Convert1BSTo1Ore {
            get {
                return ResourceManager.GetString("Convert1BSTo1Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个智慧石兑换1个能量指示物 的本地化字符串。
        /// </summary>
        internal static string Convert1BSTo1PWT {
            get {
                return ResourceManager.GetString("Convert1BSTo1PWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个智慧石兑换3点信用点 的本地化字符串。
        /// </summary>
        internal static string Convert1BSTo3Credits {
            get {
                return ResourceManager.GetString("Convert1BSTo3Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8点能量兑换2点知识 的本地化字符串。
        /// </summary>
        internal static string EightPWTo2Knowledge {
            get {
                return ResourceManager.GetString("EightPWTo2Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8点能量兑换2个量子方块 的本地化字符串。
        /// </summary>
        internal static string EightPWTo2QIC {
            get {
                return ResourceManager.GetString("EightPWTo2QIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4点信用点兑换1点知识 的本地化字符串。
        /// </summary>
        internal static string FourCreditsTo1Knowledge {
            get {
                return ResourceManager.GetString("FourCreditsTo1Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4点信用点兑换1个量子方块 的本地化字符串。
        /// </summary>
        internal static string FourCreditsTo1QIC {
            get {
                return ResourceManager.GetString("FourCreditsTo1QIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4点能量兑换1点知识 的本地化字符串。
        /// </summary>
        internal static string FourPWTo1Knowledge {
            get {
                return ResourceManager.GetString("FourPWTo1Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4点能量兑换1个量子方块 的本地化字符串。
        /// </summary>
        internal static string FourPWTo1QIC {
            get {
                return ResourceManager.GetString("FourPWTo1QIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自己所有联盟内建筑数量最多 的本地化字符串。
        /// </summary>
        internal static string FSFederationBuildings {
            get {
                return ResourceManager.GetString("FSFederationBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自己建筑所处盖亚星球数量最多 的本地化字符串。
        /// </summary>
        internal static string FSGaiaPlanets {
            get {
                return ResourceManager.GetString("FSGaiaPlanets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自己建筑数量最多 的本地化字符串。
        /// </summary>
        internal static string FSMaxBuildings {
            get {
                return ResourceManager.GetString("FSMaxBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自己建筑所处星球种类最多 的本地化字符串。
        /// </summary>
        internal static string FSPlanetTypes {
            get {
                return ResourceManager.GetString("FSPlanetTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自己卫星数量最多 的本地化字符串。
        /// </summary>
        internal static string FSSatelites {
            get {
                return ResourceManager.GetString("FSSatelites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自己建筑所处星域数量最多 的本地化字符串。
        /// </summary>
        internal static string FSSpaceSector {
            get {
                return ResourceManager.GetString("FSSpaceSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个盖亚单元兑换1点信用点 的本地化字符串。
        /// </summary>
        internal static string OneGaiaTo1Credit {
            get {
                return ResourceManager.GetString("OneGaiaTo1Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个盖亚单元兑换1个矿石 的本地化字符串。
        /// </summary>
        internal static string OneGaiaTo1Ore {
            get {
                return ResourceManager.GetString("OneGaiaTo1Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个盖亚单元兑换1个能量指示物 的本地化字符串。
        /// </summary>
        internal static string OneGaiaTo1PWT {
            get {
                return ResourceManager.GetString("OneGaiaTo1PWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个盖亚单元兑换1个量子方块 的本地化字符串。
        /// </summary>
        internal static string OneGaiaTo1QIC {
            get {
                return ResourceManager.GetString("OneGaiaTo1QIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1点知识兑换1点信用点 的本地化字符串。
        /// </summary>
        internal static string OneKnowledgeTo1Credit {
            get {
                return ResourceManager.GetString("OneKnowledgeTo1Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个矿石兑换1点信用点 的本地化字符串。
        /// </summary>
        internal static string OneOreTo1Credit {
            get {
                return ResourceManager.GetString("OneOreTo1Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个矿石兑换1个能量指示物 的本地化字符串。
        /// </summary>
        internal static string OneOreTo1PWT {
            get {
                return ResourceManager.GetString("OneOreTo1PWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1点能量兑换1点信用点 的本地化字符串。
        /// </summary>
        internal static string OnePWTo1Credit {
            get {
                return ResourceManager.GetString("OnePWTo1Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1点能量兑换2点信用点 的本地化字符串。
        /// </summary>
        internal static string OnePWTo2Credits {
            get {
                return ResourceManager.GetString("OnePWTo2Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个量子方块兑换1点信用点 的本地化字符串。
        /// </summary>
        internal static string OneQICTo1Credit {
            get {
                return ResourceManager.GetString("OneQICTo1Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个量子方块兑换1个矿石 的本地化字符串。
        /// </summary>
        internal static string OneQICTo1Ore {
            get {
                return ResourceManager.GetString("OneQICTo1Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个量子方块兑换1个能量指示物 的本地化字符串。
        /// </summary>
        internal static string OneQICTo1PWT {
            get {
                return ResourceManager.GetString("OneQICTo1PWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6点能量兑换2个矿石 的本地化字符串。
        /// </summary>
        internal static string SixPWTo2Ore {
            get {
                return ResourceManager.GetString("SixPWTo2Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3点信用点兑换1个矿石 的本地化字符串。
        /// </summary>
        internal static string ThreeCreditsTo1Ore {
            get {
                return ResourceManager.GetString("ThreeCreditsTo1Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3点能量兑换1个矿石 的本地化字符串。
        /// </summary>
        internal static string ThreePWTo1Ore {
            get {
                return ResourceManager.GetString("ThreePWTo1Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3点能量兑换2个矿石 的本地化字符串。
        /// </summary>
        internal static string ThreePWTo2Ore {
            get {
                return ResourceManager.GetString("ThreePWTo2Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2点能量兑换1点知识 的本地化字符串。
        /// </summary>
        internal static string TwoPWTo1Knowledge {
            get {
                return ResourceManager.GetString("TwoPWTo1Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2点能量兑换1个矿石和1点信用点 的本地化字符串。
        /// </summary>
        internal static string TwoPWTo1Ore1Credit {
            get {
                return ResourceManager.GetString("TwoPWTo1Ore1Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2点能量兑换1个能量指示物和1点信用点 的本地化字符串。
        /// </summary>
        internal static string TwoPWTo1PWT1Credit {
            get {
                return ResourceManager.GetString("TwoPWTo1PWT1Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2点能量兑换1个量子方块 的本地化字符串。
        /// </summary>
        internal static string TwoPWTo1QIC {
            get {
                return ResourceManager.GetString("TwoPWTo1QIC", resourceCulture);
            }
        }
    }
}
