//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaiaCore.Gaia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GaiaCore.Gaia.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 牺牲1能量1个智慧石兑换1个矿石.
        /// </summary>
        internal static string Burn1Convert1BSTo1Ore {
            get {
                return ResourceManager.GetString("Burn1Convert1BSTo1Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 牺牲1能量1个智慧石兑换3点信用点.
        /// </summary>
        internal static string Burn1Convert1BSTo3Credits {
            get {
                return ResourceManager.GetString("Burn1Convert1BSTo3Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1个智慧石和1点能量兑换1点知识.
        /// </summary>
        internal static string Convert1BS1PWTo1Knowledge {
            get {
                return ResourceManager.GetString("Convert1BS1PWTo1Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1个智慧石和1点能量兑换1个量子方块.
        /// </summary>
        internal static string Convert1BS1PWTo1QIC {
            get {
                return ResourceManager.GetString("Convert1BS1PWTo1QIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1个智慧石兑换1个矿石.
        /// </summary>
        internal static string Convert1BSTo1Ore {
            get {
                return ResourceManager.GetString("Convert1BSTo1Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1个智慧石兑换1个能量指示物.
        /// </summary>
        internal static string Convert1BSTo1PWT {
            get {
                return ResourceManager.GetString("Convert1BSTo1PWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1个智慧石兑换3点信用点.
        /// </summary>
        internal static string Convert1BSTo3Credits {
            get {
                return ResourceManager.GetString("Convert1BSTo3Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8点能量兑换2点知识.
        /// </summary>
        internal static string EightPWTo2Knowledge {
            get {
                return ResourceManager.GetString("EightPWTo2Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8点能量兑换2个量子方块.
        /// </summary>
        internal static string EightPWTo2QIC {
            get {
                return ResourceManager.GetString("EightPWTo2QIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4点信用点兑换1点知识.
        /// </summary>
        internal static string FourCreditsTo1Knowledge {
            get {
                return ResourceManager.GetString("FourCreditsTo1Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4点信用点兑换1个量子方块.
        /// </summary>
        internal static string FourCreditsTo1QIC {
            get {
                return ResourceManager.GetString("FourCreditsTo1QIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4点能量兑换1点知识.
        /// </summary>
        internal static string FourPWTo1Knowledge {
            get {
                return ResourceManager.GetString("FourPWTo1Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4点能量兑换1个量子方块.
        /// </summary>
        internal static string FourPWTo1QIC {
            get {
                return ResourceManager.GetString("FourPWTo1QIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自己所有联盟内建筑数量最多.
        /// </summary>
        internal static string FSFederationBuildings {
            get {
                return ResourceManager.GetString("FSFederationBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自己建筑所处盖亚星球数量最多.
        /// </summary>
        internal static string FSGaiaPlanets {
            get {
                return ResourceManager.GetString("FSGaiaPlanets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自己建筑数量最多.
        /// </summary>
        internal static string FSMaxBuildings {
            get {
                return ResourceManager.GetString("FSMaxBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自己建筑所处星球种类最多.
        /// </summary>
        internal static string FSPlanetTypes {
            get {
                return ResourceManager.GetString("FSPlanetTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自己卫星数量最多.
        /// </summary>
        internal static string FSSatelites {
            get {
                return ResourceManager.GetString("FSSatelites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自己建筑所处星域数量最多.
        /// </summary>
        internal static string FSSpaceSector {
            get {
                return ResourceManager.GetString("FSSpaceSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1个盖亚单元兑换1点信用点.
        /// </summary>
        internal static string OneGaiaTo1Credit {
            get {
                return ResourceManager.GetString("OneGaiaTo1Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1个盖亚单元兑换1个矿石.
        /// </summary>
        internal static string OneGaiaTo1Ore {
            get {
                return ResourceManager.GetString("OneGaiaTo1Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1个盖亚单元兑换1个能量指示物.
        /// </summary>
        internal static string OneGaiaTo1PWT {
            get {
                return ResourceManager.GetString("OneGaiaTo1PWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1个盖亚单元兑换1个量子方块.
        /// </summary>
        internal static string OneGaiaTo1QIC {
            get {
                return ResourceManager.GetString("OneGaiaTo1QIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1点知识兑换1点信用点.
        /// </summary>
        internal static string OneKnowledgeTo1Credit {
            get {
                return ResourceManager.GetString("OneKnowledgeTo1Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1个矿石兑换1点信用点.
        /// </summary>
        internal static string OneOreTo1Credit {
            get {
                return ResourceManager.GetString("OneOreTo1Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1个矿石兑换1个能量指示物.
        /// </summary>
        internal static string OneOreTo1PWT {
            get {
                return ResourceManager.GetString("OneOreTo1PWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1点能量兑换1点信用点.
        /// </summary>
        internal static string OnePWTo1Credit {
            get {
                return ResourceManager.GetString("OnePWTo1Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1点能量兑换2点信用点.
        /// </summary>
        internal static string OnePWTo2Credits {
            get {
                return ResourceManager.GetString("OnePWTo2Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1个量子方块兑换1点信用点.
        /// </summary>
        internal static string OneQICTo1Credit {
            get {
                return ResourceManager.GetString("OneQICTo1Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1个量子方块兑换1个矿石.
        /// </summary>
        internal static string OneQICTo1Ore {
            get {
                return ResourceManager.GetString("OneQICTo1Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1个量子方块兑换1个能量指示物.
        /// </summary>
        internal static string OneQICTo1PWT {
            get {
                return ResourceManager.GetString("OneQICTo1PWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6点能量兑换2个矿石.
        /// </summary>
        internal static string SixPWTo2Ore {
            get {
                return ResourceManager.GetString("SixPWTo2Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3点信用点兑换1个矿石.
        /// </summary>
        internal static string ThreeCreditsTo1Ore {
            get {
                return ResourceManager.GetString("ThreeCreditsTo1Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3点能量兑换1个矿石.
        /// </summary>
        internal static string ThreePWTo1Ore {
            get {
                return ResourceManager.GetString("ThreePWTo1Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3点能量兑换2个矿石.
        /// </summary>
        internal static string ThreePWTo2Ore {
            get {
                return ResourceManager.GetString("ThreePWTo2Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2点能量兑换1点知识.
        /// </summary>
        internal static string TwoPWTo1Knowledge {
            get {
                return ResourceManager.GetString("TwoPWTo1Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2点能量兑换1个矿石和1点信用点.
        /// </summary>
        internal static string TwoPWTo1Ore1Credit {
            get {
                return ResourceManager.GetString("TwoPWTo1Ore1Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2点能量兑换1个能量指示物和1点信用点.
        /// </summary>
        internal static string TwoPWTo1PWT1Credit {
            get {
                return ResourceManager.GetString("TwoPWTo1PWT1Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2点能量兑换1个量子方块.
        /// </summary>
        internal static string TwoPWTo1QIC {
            get {
                return ResourceManager.GetString("TwoPWTo1QIC", resourceCulture);
            }
        }
    }
}
